# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Upload to Artifactory Repository

on:
  push:
    branches: [ main ]
  

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    
    - name: Build with Maven
      run: mvn clean install
      
  #  - name: Upload to Artifactory
    #  run:  curl -X PUT -u admin:Vishali@1503 -T /home/runner/work/Artifactory/Artifactory/target/SubmissionDataForm-0.0.1-SNAPSHOT.jar "http://localhost:8081/artifactory/CG-libs-release-local/SubmissionDataForm-0.0.1-SNAPSHOT.jar"
